/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VlogRouteImport } from './routes/vlog'
import { Route as EspecialidadesRouteImport } from './routes/especialidades'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVlogRouteImport } from './routes/admin.vlog'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const VlogRoute = VlogRouteImport.update({
  id: '/vlog',
  path: '/vlog',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesRoute = EspecialidadesRouteImport.update({
  id: '/especialidades',
  path: '/especialidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVlogRoute = AdminVlogRouteImport.update({
  id: '/vlog',
  path: '/vlog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/vlog': typeof VlogRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vlog': typeof AdminVlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/vlog': typeof VlogRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vlog': typeof AdminVlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/especialidades': typeof EspecialidadesRoute
  '/vlog': typeof VlogRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vlog': typeof AdminVlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/especialidades'
    | '/vlog'
    | '/admin/blog'
    | '/admin/usuarios'
    | '/admin/vlog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/especialidades'
    | '/vlog'
    | '/admin/blog'
    | '/admin/usuarios'
    | '/admin/vlog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contato'
    | '/especialidades'
    | '/vlog'
    | '/admin/blog'
    | '/admin/usuarios'
    | '/admin/vlog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  EspecialidadesRoute: typeof EspecialidadesRoute
  VlogRoute: typeof VlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vlog': {
      id: '/vlog'
      path: '/vlog'
      fullPath: '/vlog'
      preLoaderRoute: typeof VlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades': {
      id: '/especialidades'
      path: '/especialidades'
      fullPath: '/especialidades'
      preLoaderRoute: typeof EspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vlog': {
      id: '/admin/vlog'
      path: '/vlog'
      fullPath: '/admin/vlog'
      preLoaderRoute: typeof AdminVlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVlogRoute: typeof AdminVlogRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVlogRoute: AdminVlogRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  EspecialidadesRoute: EspecialidadesRoute,
  VlogRoute: VlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
